<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xuman</groupId>
        <artifactId>xuman-cloud</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>xuman-modules</artifactId>
    <packaging>pom</packaging>
    <description>业务模块</description>

    <modules>
        <module>xuman-system</module>
        <module>xuman-tenant</module>
        <module>xuman-gen</module>
        <module>xuman-job</module>
        <module>xuman-file</module>
        <module>xuman-workflow</module>
        <module>xuman-open</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
