<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.han</groupId>
        <artifactId>han-api</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>han-api-open</artifactId>
    <description>开放平台服务接口（@HttpExchange声明式HTTP客户端）</description>

    <dependencies>
        <dependency>
            <groupId>com.han</groupId>
            <artifactId>han-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
    </dependencies>
</project>
