server:
  port: 9207
  forward-headers-strategy: framework

spring:
  config:
    import:
      - "optional:nacos:application-shared.yml"
      - "optional:nacos:han-file.yml"
  application:
    name: han-file
  servlet:
    multipart:
      max-file-size: ${HAN_FILE_MAX_FILE_SIZE:300MB}
      max-request-size: ${HAN_FILE_MAX_REQUEST_SIZE:320MB}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:han}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:han@2026}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:han}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:han@2026}
        file-extension: yml
