server:
  port: 8080

spring:
  application:
    name: xuman-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: xuman
      config:
        server-addr: localhost:8848
        namespace: xuman
        file-extension: yml
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            # 认证中心
            - id: xuman-auth
              uri: lb://xuman-auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=0

            # 系统服务
            - id: xuman-system
              uri: lb://xuman-system
              predicates:
                - Path=/system/**
              filters:
                - StripPrefix=0

            # 租户服务
            - id: xuman-tenant
              uri: lb://xuman-tenant
              predicates:
                - Path=/tenant/**
              filters:
                - StripPrefix=0

            # 代码生成
            - id: xuman-gen
              uri: lb://xuman-gen
              predicates:
                - Path=/gen/**
              filters:
                - StripPrefix=0

            # 定时任务
            - id: xuman-job
              uri: lb://xuman-job
              predicates:
                - Path=/job/**
              filters:
                - StripPrefix=0

            # 文件服务
            - id: xuman-file
              uri: lb://xuman-file
              predicates:
                - Path=/file/**
              filters:
                - StripPrefix=0

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# 日志配置
logging:
  level:
    com.xuman: debug
    org.springframework.cloud.gateway: debug
