-- AIVideo shot-level sound cue persistence.
-- Purpose: persist BGM and SFX cues generated during asset extraction for later TTS/mix/edit stages.

ALTER TABLE ai_video_shot
    ADD COLUMN IF NOT EXISTS bgm_cue TEXT;

ALTER TABLE ai_video_shot
    ADD COLUMN IF NOT EXISTS sfx_cues TEXT;

COMMENT ON COLUMN ai_video_shot.bgm_cue IS 'Shot-level BGM cue generated by AIVideo asset extraction';
COMMENT ON COLUMN ai_video_shot.sfx_cues IS 'Shot-level SFX/environment sound cues generated by AIVideo asset extraction';
