<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xuman</groupId>
        <artifactId>xuman-starter</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>xuman-starter-storage</artifactId>
    <description>存储Starter - 支持本地/MinIO/OSS可插拔</description>

    <dependencies>
        <dependency>
            <groupId>com.xuman</groupId>
            <artifactId>xuman-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- AWS S3 SDK (RustFS 兼容) -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>2.25.27</version>
        </dependency>
    </dependencies>

</project>
