server:
  port: 9205

spring:
  config:
    import:
      - "optional:nacos:application-shared.yml"
      - "optional:nacos:han-open.yml"
  application:
    name: han-open
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:han}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:han@2026}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:han}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:han@2026}
        file-extension: yml
