server:
  port: 9100

spring:
  application:
    name: xuman-monitor
  security:
    user:
      name: admin
      password: admin123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: xuman
  boot:
    admin:
      ui:
        title: XuMan监控中心
